replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: hello-world

service:
  type: ClusterIP
  port: 80
